version: '3.8'

services:
  tensorrt:
    container_name: tensorrt
    build:
      dockerfile: ./Dockerfile
      context: .
    image: tensorrt:latest
    command: >
      sh -c "nvidia-smi && 
             cd /app && 
             python3 main.py --onnx --engine --run"
    network_mode: "host"
    volumes:
      - ./data:/app/data:rw
      - ./nets:/app/nets:rw
      - ./utils:/app/utils:rw
      - ./outputs:/app/outputs:rw
      - ./weights:/app/weights:rw
      - ./main.py:/app/main.py:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    runtime: nvidia  # Use NVIDIA runtime for GPU acceleration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]